"""Declarative tracker-label to canonical-ID mappings.

Raw tracker labels belong only here. Display code consumes canonical IDs and
therefore cannot accidentally expose one provider's terminology.
"""

from hakubun.genres.models import GenreTag


_CATEGORY_IDS = {
    'genre': (
        'action', 'adventure', 'avant_garde', 'boys_love', 'comedy',
        'drama', 'ecchi', 'fantasy', 'girls_love', 'gourmet', 'horror',
        'mystery', 'psychological', 'romance', 'sci_fi', 'slice_of_life',
        'sports', 'supernatural', 'suspense', 'erotica', 'hentai',
    ),
    'theme': (
        'adult_cast', 'anthropomorphic', 'cgdct', 'childcare',
        'combat_sports', 'crossdressing', 'delinquents', 'detective',
        'educational', 'gag_humor', 'gore', 'harem', 'historical', 'idols',
        'isekai', 'iyashikei', 'magical_girl', 'martial_arts', 'mecha',
        'military', 'music', 'mythology', 'parody', 'performing_arts',
        'racing', 'reincarnation', 'reverse_harem', 'samurai', 'school',
        'space', 'super_power', 'survival', 'time_travel', 'vampire',
        'video_games', 'workplace', 'award_winning', 'high_stakes_game',
        'love_polygon', 'love_status_quo', 'magical_sex_shift', 'medical',
        'otaku_culture', 'pets', 'showbiz', 'strategy_game', 'team_sports',
        'urban_fantasy', 'villainess', 'visual_arts', 'asia', 'china',
        'japan', 'earth', 'modern_day', 'sexual_content', 'serialized_story',
    ),
    'demographic': ('kids', 'shounen', 'shoujo', 'seinen', 'josei'),
}

CANONICAL_TAGS = {
    tag_id: GenreTag(tag_id, category)
    for category, ids in _CATEGORY_IDS.items() for tag_id in ids
}
CANONICAL_ORDER = tuple(CANONICAL_TAGS)


# Explicit aliases are intentionally provider-scoped. Similar-looking labels
# are never guessed dynamically; adding a tracker spelling is a data edit.
TRACKER_GENRE_MAP = {
    # MyAnimeList genres, themes, and demographics.
    ('mal', 'Action'): 'action',
    ('mal', 'Adventure'): 'adventure',
    ('mal', 'Avant Garde'): 'avant_garde',
    ('mal', 'Boys Love'): 'boys_love',
    ('mal', 'Comedy'): 'comedy',
    ('mal', 'Drama'): 'drama',
    ('mal', 'Ecchi'): 'ecchi',
    ('mal', 'Fantasy'): 'fantasy',
    ('mal', 'Girls Love'): 'girls_love',
    ('mal', 'Gourmet'): 'gourmet',
    ('mal', 'Horror'): 'horror',
    ('mal', 'Mystery'): 'mystery',
    ('mal', 'Psychological'): 'psychological',
    ('mal', 'Romance'): 'romance',
    ('mal', 'Sci-Fi'): 'sci_fi',
    ('mal', 'Slice of Life'): 'slice_of_life',
    ('mal', 'Sports'): 'sports',
    ('mal', 'Supernatural'): 'supernatural',
    ('mal', 'Suspense'): 'suspense',
    ('mal', 'Erotica'): 'erotica',
    ('mal', 'Hentai'): 'hentai',
    ('mal', 'Adult Cast'): 'adult_cast',
    ('mal', 'Anthropomorphic'): 'anthropomorphic',
    ('mal', 'CGDCT'): 'cgdct',
    ('mal', 'Childcare'): 'childcare',
    ('mal', 'Combat Sports'): 'combat_sports',
    ('mal', 'Crossdressing'): 'crossdressing',
    ('mal', 'Delinquents'): 'delinquents',
    ('mal', 'Detective'): 'detective',
    ('mal', 'Educational'): 'educational',
    ('mal', 'Gag Humor'): 'gag_humor',
    ('mal', 'Gore'): 'gore',
    ('mal', 'Harem'): 'harem',
    ('mal', 'Historical'): 'historical',
    ('mal', 'Idols (Female)'): 'idols',
    ('mal', 'Idols (Male)'): 'idols',
    ('mal', 'Isekai'): 'isekai',
    ('mal', 'Iyashikei'): 'iyashikei',
    ('mal', 'Mahou Shoujo'): 'magical_girl',
    ('mal', 'Martial Arts'): 'martial_arts',
    ('mal', 'Mecha'): 'mecha',
    ('mal', 'Military'): 'military',
    ('mal', 'Music'): 'music',
    ('mal', 'Mythology'): 'mythology',
    ('mal', 'Parody'): 'parody',
    ('mal', 'Performing Arts'): 'performing_arts',
    ('mal', 'Racing'): 'racing',
    ('mal', 'Reincarnation'): 'reincarnation',
    ('mal', 'Reverse Harem'): 'reverse_harem',
    ('mal', 'Samurai'): 'samurai',
    ('mal', 'School'): 'school',
    ('mal', 'Space'): 'space',
    ('mal', 'Super Power'): 'super_power',
    ('mal', 'Survival'): 'survival',
    ('mal', 'Time Travel'): 'time_travel',
    ('mal', 'Vampire'): 'vampire',
    ('mal', 'Video Game'): 'video_games',
    ('mal', 'Workplace'): 'workplace',
    ('mal', 'Award Winning'): 'award_winning',
    ('mal', 'High Stakes Game'): 'high_stakes_game',
    ('mal', 'Love Polygon'): 'love_polygon',
    ('mal', 'Love Status Quo'): 'love_status_quo',
    ('mal', 'Magical Sex Shift'): 'magical_sex_shift',
    ('mal', 'Medical'): 'medical',
    ('mal', 'Otaku Culture'): 'otaku_culture',
    ('mal', 'Pets'): 'pets',
    ('mal', 'Showbiz'): 'showbiz',
    ('mal', 'Strategy Game'): 'strategy_game',
    ('mal', 'Team Sports'): 'team_sports',
    ('mal', 'Urban Fantasy'): 'urban_fantasy',
    ('mal', 'Villainess'): 'villainess',
    ('mal', 'Visual Arts'): 'visual_arts',
    ('mal', 'Kids'): 'kids',
    ('mal', 'Shounen'): 'shounen',
    ('mal', 'Shoujo'): 'shoujo',
    ('mal', 'Seinen'): 'seinen',
    ('mal', 'Josei'): 'josei',

    # AniList genres plus recognized MediaTag names.
    ('anilist', 'Action'): 'action',
    ('anilist', 'Adventure'): 'adventure',
    ('anilist', 'Comedy'): 'comedy',
    ('anilist', 'Drama'): 'drama',
    ('anilist', 'Ecchi'): 'ecchi',
    ('anilist', 'Fantasy'): 'fantasy',
    ('anilist', 'Horror'): 'horror',
    ('anilist', 'Mahou Shoujo'): 'magical_girl',
    ('anilist', 'Mecha'): 'mecha',
    ('anilist', 'Music'): 'music',
    ('anilist', 'Mystery'): 'mystery',
    ('anilist', 'Psychological'): 'psychological',
    ('anilist', 'Romance'): 'romance',
    ('anilist', 'Sci-Fi'): 'sci_fi',
    ('anilist', 'Slice of Life'): 'slice_of_life',
    ('anilist', 'Sports'): 'sports',
    ('anilist', 'Supernatural'): 'supernatural',
    ('anilist', 'Thriller'): 'suspense',
    ('anilist', 'Hentai'): 'hentai',
    ('anilist', 'Boys Love'): 'boys_love',
    ('anilist', 'Yuri'): 'girls_love',
    ('anilist', 'Cute Girls Doing Cute Things'): 'cgdct',
    ('anilist', 'School'): 'school',
    ('anilist', 'Video Games'): 'video_games',
    ('anilist', 'Isekai'): 'isekai',
    ('anilist', 'Iyashikei'): 'iyashikei',
    ('anilist', 'Martial Arts'): 'martial_arts',
    ('anilist', 'Military'): 'military',
    ('anilist', 'Historical'): 'historical',
    ('anilist', 'Idol'): 'idols',
    ('anilist', 'Idols'): 'idols',
    ('anilist', 'Parody'): 'parody',
    ('anilist', 'Samurai'): 'samurai',
    ('anilist', 'Space'): 'space',
    ('anilist', 'Super Power'): 'super_power',
    ('anilist', 'Survival'): 'survival',
    ('anilist', 'Time Manipulation'): 'time_travel',
    ('anilist', 'Vampire'): 'vampire',
    ('anilist', 'Work'): 'workplace',
    ('anilist', 'Shounen'): 'shounen',
    ('anilist', 'Shoujo'): 'shoujo',
    ('anilist', 'Seinen'): 'seinen',
    ('anilist', 'Josei'): 'josei',
    ('anilist', 'Kids'): 'kids',

    # Kitsu category titles, including older labels still returned by REST.
    ('kitsu', 'Action'): 'action',
    ('kitsu', 'Adventure'): 'adventure',
    ('kitsu', 'Comedy'): 'comedy',
    ('kitsu', 'Drama'): 'drama',
    ('kitsu', 'Ecchi'): 'ecchi',
    ('kitsu', 'Fantasy'): 'fantasy',
    ('kitsu', 'Horror'): 'horror',
    ('kitsu', 'Mystery'): 'mystery',
    ('kitsu', 'Psychological'): 'psychological',
    ('kitsu', 'Romance'): 'romance',
    ('kitsu', 'Science Fiction'): 'sci_fi',
    ('kitsu', 'Sci-Fi'): 'sci_fi',
    ('kitsu', 'Slice of Life'): 'slice_of_life',
    ('kitsu', 'Sports'): 'sports',
    ('kitsu', 'Supernatural'): 'supernatural',
    ('kitsu', 'Thriller'): 'suspense',
    ('kitsu', 'Yaoi'): 'boys_love',
    ('kitsu', 'Boys Love'): 'boys_love',
    ('kitsu', 'Yuri'): 'girls_love',
    ('kitsu', 'Girls Love'): 'girls_love',
    ('kitsu', 'School Life'): 'school',
    ('kitsu', 'School'): 'school',
    ('kitsu', 'Video Games'): 'video_games',
    ('kitsu', 'Game'): 'video_games',
    ('kitsu', 'Isekai'): 'isekai',
    ('kitsu', 'Iyashikei'): 'iyashikei',
    ('kitsu', 'Magical Girl'): 'magical_girl',
    ('kitsu', 'Martial Arts'): 'martial_arts',
    ('kitsu', 'Mecha'): 'mecha',
    ('kitsu', 'Military'): 'military',
    ('kitsu', 'Music'): 'music',
    ('kitsu', 'Historical'): 'historical',
    ('kitsu', 'Parody'): 'parody',
    ('kitsu', 'Samurai'): 'samurai',
    ('kitsu', 'Space'): 'space',
    ('kitsu', 'Super Power'): 'super_power',
    ('kitsu', 'Vampire'): 'vampire',
    ('kitsu', 'Shounen'): 'shounen',
    ('kitsu', 'Shoujo'): 'shoujo',
    ('kitsu', 'Seinen'): 'seinen',
    ('kitsu', 'Josei'): 'josei',
    ('kitsu', 'Kids'): 'kids',
    ('kitsu', 'Asia'): 'asia',
    ('kitsu', 'China'): 'china',
    ('kitsu', 'Japan'): 'japan',
    ('kitsu', 'Earth'): 'earth',
    ('kitsu', 'Present'): 'modern_day',
    ('kitsu', 'Nudity'): 'sexual_content',
    ('kitsu', 'Boxing'): 'combat_sports',
    ('kitsu', 'Combat'): 'action',
    ('kitsu', 'School Clubs'): 'school',
    ('kitsu', 'Slapstick'): 'gag_humor',
    ('kitsu', 'Superhero'): 'super_power',
    ('kitsu', 'Time Travel'): 'time_travel',
    ('kitsu', 'Plot Continuity'): 'serialized_story',
}

_NORMALIZED_TRACKER_GENRE_MAP = {
    (source, ' '.join(raw.split()).casefold()): canonical_id
    for (source, raw), canonical_id in TRACKER_GENRE_MAP.items()
}


def canonical_id_for(provider, label):
    """Exact provider mapping with case/spacing-insensitive lookup."""
    provider = str(provider or '').lower()
    wanted = ' '.join(str(label or '').split()).casefold()
    return _NORMALIZED_TRACKER_GENRE_MAP.get((provider, wanted))
